name: dispatched build-docker-image

on:
  push:
    branches:
      - master
  repository_dispatch:
    types:
      - dispatch-build

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    if: github.repository == 'opensciencegrid/osgvo-docker-pilot'
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

  build:
    runs-on: ubuntu-latest
    if: github.repository == 'opensciencegrid/osgvo-docker-pilot'
    strategy:
      matrix:
        repo: ['development', 'testing', 'release']

    steps:
    - name: checkout osgvo-docker-pilot
      uses: actions/checkout@v2

    - id: generate-tag-list
      env:
        REPO: ${{ matrix.repo }}
        TIMESTAMP: ${{ needs.make-date-tag.outputs.dtag }}
      run: |
        docker_repo=opensciencegrid/osgvo-docker-pilot
        tag_list=$docker_repo:$REPO,$docker_repo:$REPO-$TIMESTAMP
        echo "::set-output name=taglist::$tag_list"

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: opensciencegrid/osgvo-docker-pilot
        push: true
        build-args: BASE_YUM_REPO=${{ matrix.repo }}
        tags: "${{ steps.generate-tag-list.outputs.taglist }}"

