name: Build and test container images

on:
  push:
  pull_request:
  repository_dispatch:
    types:
      - dispatch-build
  workflow_dispatch:

jobs:
#   make-date-tag:
#     runs-on: ubuntu-latest
#     outputs:
#       dtag: ${{ steps.mkdatetag.outputs.dtag }}
#     steps:
#     - name: make date tag
#       id: mkdatetag
#       run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        osg_series: ['3.6']
        repo: ['development', 'testing', 'release']
        image_name: ['test']
    steps:
      - uses: AidenCohen31/build-container-action@v9.2
        with:
          osg_series: ${{ matrix.osg_series }}
          repo: ${{ matrix.repo }}
          image_name: ${{ matrix.image_name }}
  test:
    runs-on: ubuntu-20.04
    needs: [build]
    strategy:
      fail-fast: false
      matrix:
        osg_series: ['3.6']
        repo: ['development', 'testing', 'release']
        runtime: ['docker', 'singularity']
        cvmfs: ['bindmount', 'cvmfsexec']
        exclude:
          - runtime: singularity
            cvmfs: cvmfsexec
    steps:
      - uses: AidenCohen31/load-container-action@v5
        id: load-image
        with:
          osg_series: ${{ matrix.osg_series }}
          repo: ${{ matrix.repo }}
          timestamp_tag: ${{ needs.build.outputs.tags }}
      - name: Run tests
        env:
          CONTAINER_RUNTIME: ${{ matrix.runtime }}
          CVMFS_INSTALL: ${{ matrix.cvmfs }}
          CONTAINER_IMAGE: ${{ steps.load-image.outputs.image_tag }}
        run: |
          sudo ./tests/test_inside_gha.sh "$CONTAINER_RUNTIME" \
                                          "$CVMFS_INSTALL" \
                                          "$CONTAINER_IMAGE"
  push:
    runs-on: ubuntu-latest
    needs: [build, test]
    if: >-
      github.ref == 'refs/heads/master' &&
      github.event_name != 'pull_request' &&
      github.repository_owner == 'opensciencegrid'
    strategy:
      matrix:
        osg_series: ['3.6']
        repo: ['development', 'testing', 'release']
        registry:
          - url: hub.opensciencegrid.org
            username: OSG_HARBOR_ROBOT_USER
            password: OSG_HARBOR_ROBOT_PASSWORD
          - url: docker.io
            username: DOCKER_USERNAME
            password: DOCKER_PASSWORD
    steps:
      - uses: AidenCohen31/push-container-action@v3
        with:
          osg_series: ${{ matrix.osg_series }}
          repo: ${{ matrix.repo }}
          timestamp_tag: ${{ needs.build.outputs.tags }}
          registry_url: ${{ matrix.registry.url }}
          registry_user: ${{ secrets[matrix.registry.username] }}
          registry_pass: ${{ secrets[matrix.registry.password] }}
